services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://admin:password@db/cafe_manager  # Update with actual credentials
      - ALLOWED_ORIGINS=http://localhost:3000

  db:
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: StrongPassword  # Change this to a strong password
      MYSQL_DATABASE: cafe_manager  # Change to your desired database name
      MYSQL_USER: admin  # Change to your desired username
      MYSQL_PASSWORD: password  # Change to your desired password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: